# Generated by Django 5.2.4 on 2025-08-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petInfoSys', '0014_pet_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='remarks',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
