# Generated by Django 5.2.4 on 2025-10-16 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petInfoSys', '0021_auto_20250918_1453'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('breed', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=255)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('sex', models.CharField(max_length=50)),
                ('remarks', models.CharField(blank=True, max_length=350, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
