# Generated by Django 5.2.4 on 2025-10-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petInfoSys', '0026_alter_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkinappointment',
            name='request',
            field=models.CharField(default='accepted', max_length=20),
        ),
    ]
