# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['Desktop_Application\\Frontend\\main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('Desktop_Application', 'Desktop_Application'),
        ('Desktop_Application/Frontend/ui-files', 'ui-files'),
        ('Desktop_Application/Frontend/font', 'font'),
        ('Desktop_Application/Frontend/Icons', 'Icons'),
        ('Desktop_Application/Frontend/image', 'image'),
        ('Desktop_Application/Frontend/AddressJSON', 'AddressJSON'),
        ('Desktop_Application/Frontend/Config', 'Config'),
    ],
    hiddenimports=[
        'Desktop_Application.Frontend.app',
        'Desktop_Application.Frontend.addServicePopUp',
        'Desktop_Application.Frontend.analytics',
        'Desktop_Application.Frontend.api_client',
        'Desktop_Application.Frontend.api_worker',
        'Desktop_Application.Frontend.app_optimizations',
        'Desktop_Application.Frontend.appointmentPopUp',
        'Desktop_Application.Frontend.async_helper',
        'Desktop_Application.Frontend.config_loader',
        'Desktop_Application.Frontend.confirm_card',
        'Desktop_Application.Frontend.delete',
        'Desktop_Application.Frontend.duplicateDialog',
        'Desktop_Application.Frontend.first_time_setup_dialog',
        'Desktop_Application.Frontend.input_styles',
        'Desktop_Application.Frontend.loading_overlay',
        'Desktop_Application.Frontend.login_dialog',
        'Desktop_Application.Frontend.main',
        'Desktop_Application.Frontend.ReminderPopUp',
        'Desktop_Application.Frontend.shadowEffects',
        'Desktop_Application.Frontend.skeleton_loader',
        'Desktop_Application.Frontend.smart_loading',
        'Desktop_Application.Frontend.toast',
        'Desktop_Application.Frontend.ui_utils',
        'Desktop_Application.Frontend.uiLogic',
        'Desktop_Application.Frontend.updateFunction',
        'Desktop_Application.petInfoSys.admin',
        'Desktop_Application.petInfoSys.api_client',
        'Desktop_Application.petInfoSys.apps',
        'Desktop_Application.petInfoSys.authentication',
        'Desktop_Application.petInfoSys.models',
        'Desktop_Application.petInfoSys.serializers',
        'Desktop_Application.petInfoSys.sms_utils',
        'Desktop_Application.petInfoSys.tests',
        'Desktop_Application.petInfoSys.urls',
        'Desktop_Application.petInfoSys.views',
        'http',
        'http.client',
        'PyQt6.uic',
        'PyQt6.QtCore',
        'PyQt6.QtGui',
        'PyQt6.QtCharts',
        'PyQt6.QtWidgets',
        'requests',
        'Desktop_Application.Frontend.resources_rc',
        'requests',
        'webbrowser',
        'json',
        'threading',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='PetMate',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,  # Hide console window
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='desktopIcon.ico',
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='PetMate',
)
