
# PARA MARUN ANG JSON FILE SA LOOB NG DOCKER NGINX

server {
    listen 80;

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
    }

    # Allow serving JSON files
    location ~ \.json$ {
        root /usr/share/nginx/html;
        add_header Content-Type application/json;
    }
}
