# Generated by Django 5.2.4 on 2025-08-04 17:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petInfoSys', '0006_walkinappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkinappointment',
            name='prefTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
