# Generated by Django 5.2.4 on 2025-08-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petInfoSys', '0008_alter_walkinappointment_preftime'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkinappointment',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
