# Generated by Django 5.2.4 on 2025-08-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petInfoSys', '0010_walkinappointment_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
