# Generated by Django 5.2.4 on 2025-08-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petInfoSys', '0012_basicinfo_middlename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='middleName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
