# Generated by Django 5.2.4 on 2025-08-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petInfoSys', '0013_alter_basicinfo_middlename'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='birthDay',
            field=models.DateField(blank=True, null=True),
        ),
    ]
