# Generated by Django 5.2.4 on 2025-09-05 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petInfoSys', '0016_remove_pet_age_pet_stored_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('new', 'New Client'), ('returning', 'Returning Client')], max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('emergency_contact', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('barangay', models.CharField(max_length=100)),
                ('detailed_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pclients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_reason', models.CharField(choices=[('vaccination', 'Vaccination'), ('checkup', 'Check-up'), ('surgery', 'Surgery'), ('consultations', 'Consultations'), ('deworming', 'Deworming')], max_length=50)),
                ('provider', models.CharField(choices=[('dr_gonzales', 'Dr. Gonzales'), ('dr_domasian', 'Dr. Domasian'), ('dr_jerusalem', 'Dr. Jerusalem'), ('dr_moleno', 'Dr. Moleno')], max_length=100)),
                ('appointment_datetime', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, max_length=400, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='petInfoSys.pet')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='petInfoSys.client')),
            ],
            options={
                'db_table': 'pappointment_types',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PetWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('other', 'Other')], max_length=20)),
                ('breed', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='petInfoSys.client')),
            ],
            options={
                'db_table': 'ppets',
                'ordering': ['-created_at'],
            },
        ),
    ]
