# Generated by Django 5.2.4 on 2025-09-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petInfoSys', '0019_alter_appointmenttype_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenttype',
            name='booking_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='walkinappointment',
            name='booking_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
