# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('ui-files', 'ui-files'),
        ('Icons', 'Icons'),
        ('AddressJSON', 'AddressJSON'),
        ('Config', 'Config'),
        ('font', 'font'),
        ('addServicePopUp.py', '.'),
        ('analytics.py', '.'),
        ('api_client.py', '.'),
        ('api_worker.py', '.'),
        ('app_optimizations.py', '.'),
        ('app.py', '.'),
        ('appointmentPopUp.py', '.'),
        ('async_helper.py', '.'),
        ('config_loader.py', '.'),
        ('confirm_card.py', '.'),
        ('delete.py', '.'),
        ('duplicateDialog.py', '.'),
        ('first_time_setup_dialog.py', '.'),
        ('input_styles.py', '.'),
        ('loading_overlay.py', '.'),
        ('login_dialog.py', '.'),
        ('main.py', '.'),
        ('ReminderPopUp.py', '.'),
        ('resources_rc.py', '.'),
        ('shadowEffects.py', '.'),
        ('skeleton_loader.py', '.'),
        ('smart_loading.py', '.'),
        ('toast.py', '.'),
        ('ui_utils.py', '.'),
        ('uiLogic.py', '.'),
        ('updateFunction.py', '.'),
    ],
    hiddenimports=[
        'addServicePopUp',
        'analytics',
        'api_client',
        'api_worker',
        'app_optimizations',
        'app',
        'appointmentPopUp',
        'async_helper',
        'config_loader',
        'confirm_card',
        'delete',
        'duplicateDialog',
        'first_time_setup_dialog',
        'input_styles',
        'loading_overlay',
        'login_dialog',
        'main',
        'ReminderPopUp',
        'resources_rc',
        'shadowEffects',
        'skeleton_loader',
        'smart_loading',
        'toast',
        'ui_utils',
        'uiLogic',
        'updateFunction',
        'PyQt6.uic',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='PetMate',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['desktopIcon.ico'],
)
