# Generated by Django 5.2.4 on 2025-08-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petInfoSys', '0009_walkinappointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkinappointment',
            name='service_name',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
