"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2a1.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env_path = BASE_DIR / ".env"
load_dotenv(env_path)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/dev/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    ".ngrok.io",
    ".ngrok-free.app",
    "triggerless-brianna-pseudoviperous.ngrok-free.dev",
    ".railway.app",  # For Railway deployment
    os.getenv('RAILWAY_PUBLIC_DOMAIN', ''),  # Railway auto domain
    "petmate-desktop-application.vercel.app",  # Frontend deployed URL (no scheme/ slash)
    "api.petmateanimalclinic.com",  # Custom backend domain
    "www.petmateanimalclinic.com",  # Custom frontend domain
    "petmateanimalclinic.com",  # Root domain
]
# Remove empty strings from ALLOWED_HOSTS
ALLOWED_HOSTS = [host for host in ALLOWED_HOSTS if host]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'corsheaders',
    'petInfoSys',
    'rest_framework',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# Optional transactional email via SendGrid (HTTP API) to avoid SMTP blocks.
SENDGRID_API_KEY = os.getenv('SENDGRID_API_KEY', '')
if SENDGRID_API_KEY:
    INSTALLED_APPS.append('anymail')

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add WhiteNoise for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/dev/ref/settings/#databases


# ===========================
# EMAIL CONFIGURATION (GMAIL)
# ===========================
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', '15'))

if SENDGRID_API_KEY:
    EMAIL_BACKEND = 'anymail.backends.sendgrid.EmailBackend'
    ANYMAIL = {
        'SENDGRID_API_KEY': SENDGRID_API_KEY,
    }
    # Required for SendGrid:
    # - Use an address on your OWN domain (e.g., noreply@yourdomain.com)
    # - Verify it via SendGrid Sender Authentication (Domain Authentication or Single Sender)
    # Using a Gmail address here will typically show "via sendgrid.net" and hurt deliverability.
    DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL') or 'webmaster@localhost'
    SERVER_EMAIL = os.getenv('SERVER_EMAIL') or DEFAULT_FROM_EMAIL
    # Optional: where customer replies should go (e.g., a monitored inbox).
    DEFAULT_REPLY_TO_EMAIL = os.getenv('DEFAULT_REPLY_TO_EMAIL', '')

    # Where "Contact Us" messages should be delivered.
    # This is often a Gmail inbox even when SendGrid is used for sending.
    CONTACT_US_INBOX_EMAIL = os.getenv('CONTACT_US_INBOX_EMAIL', '') or DEFAULT_REPLY_TO_EMAIL
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False') == 'True'

    # Default ports: TLS=587, SSL=465
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', '465' if EMAIL_USE_SSL else '587'))

    # TLS and SSL should not both be enabled.
    EMAIL_USE_TLS = (os.getenv('EMAIL_USE_TLS', 'True') == 'True') and not EMAIL_USE_SSL
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')

    # Default sender. Keep it valid even if env vars are missing.
    DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL') or EMAIL_HOST_USER or 'webmaster@localhost'
    SERVER_EMAIL = os.getenv('SERVER_EMAIL') or DEFAULT_FROM_EMAIL
    DEFAULT_REPLY_TO_EMAIL = os.getenv('DEFAULT_REPLY_TO_EMAIL', '')

    # Where "Contact Us" messages should be delivered.
    CONTACT_US_INBOX_EMAIL = os.getenv('CONTACT_US_INBOX_EMAIL', '') or DEFAULT_REPLY_TO_EMAIL or EMAIL_HOST_USER


# ===========================
# SMS CONFIGURATION (PhilSMS)
# ===========================



PHILSMS_API_KEY = os.getenv('PHILSMS_API_KEY', '')
PHILSMS_SENDER_ID = os.getenv('PHILSMS_SENDER_ID', 'PhilSms')
PHILSMS_API_URL = 'https://dashboard.philsms.com/api/v3/sms/send'
PHILSMS_BALANCE_URL = 'https://dashboard.philsms.com/api/v3/sms/'


# Database configuration with connection pooling and optimization
# Priority: MYSQL_URL > Railway vars (MYSQLHOST) > Local docker-compose (DB_HOST)

# Database connection pooling configuration (PyMySQL supports connection pool)
DB_CONFIG = {
    'CONN_MAX_AGE': 600,  # Persistent connections (10 minutes)
    'CONN_HEALTH_CHECKS': True,  # Health check before using connection
    'OPTIONS': {
        'charset': 'utf8mb4',  # Better UTF-8 support
        'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
    },
    'AUTOCOMMIT': True,  # Use autocommit for better performance
}

if os.getenv('MYSQL_URL'):
    # Railway deployment - use the full connection URL
    DATABASES = {
        'default': dj_database_url.config(
            default=os.getenv('MYSQL_URL'),
            conn_max_age=DB_CONFIG['CONN_MAX_AGE'],
            conn_health_checks=DB_CONFIG['CONN_HEALTH_CHECKS'],
        )
    }
    # Merge options
    DATABASES['default'].update(DB_CONFIG)
elif os.getenv('MYSQLHOST'):
    # Railway deployment - use individual MySQL variables
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('MYSQLDATABASE', 'railway'),
            'USER': os.getenv('MYSQLUSER', 'root'),
            'PASSWORD': os.getenv('MYSQLPASSWORD'),
            'HOST': os.getenv('MYSQLHOST'),
            'PORT': os.getenv('MYSQLPORT', '3306'),
            **DB_CONFIG
        }
    }
else:
    # Local development with docker-compose
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME', 'informationsystem'),
            'USER': os.getenv('DB_USER', 'root'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'password'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '3306'),
            **DB_CONFIG
        }
    }

# Cache configuration for API responses (reduces database queries)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'pet-clinic-cache',
        'TIMEOUT': 300,  # 5 minutes default timeout
        'OPTIONS': {
            'MAX_ENTRIES': 10000,  # Increase cache size
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/dev/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/dev/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/dev/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",  # where your working CSS & images are
]
STATIC_ROOT = BASE_DIR / "staticfiles"  # where collectstatic will copy them
TEMPLATES[0]['DIRS'] = [BASE_DIR / "templates"]  # global templates

# WhiteNoise configuration for static files in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/dev/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework Settings with optimizations
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'petInfoSys.authentication.CsrfExemptSessionAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,  # Optimize pagination - return smaller page sizes
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        # NOTE: Desktop client may call some endpoints without session auth, which counts as "anon".
        # Increase these in dev to avoid frequent 429 while iterating.
        'anon': os.getenv('DRF_THROTTLE_ANON', '10000/hour' if DEBUG else '100/hour'),
        'user': os.getenv('DRF_THROTTLE_USER', '100000/hour' if DEBUG else '1000/hour'),
    },
    'DEFAULT_METADATA_CLASS': None,  # Disable metadata for OPTIONS requests (reduces overhead)
}

# Cache timeouts for different data types
CACHE_TIMEOUTS = {
    'PATIENTS': 300,  # 5 minutes
    'PETS': 300,  # 5 minutes
    'SERVICES': 600,  # 10 minutes
    'SERVICE_TYPES': 1800,  # 30 minutes (rarely changes)
    'STAFF': 1800,  # 30 minutes
    'REMINDERS': 180,  # 3 minutes
}

#-----------------------WEB APP------------------------
# CORS Settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:8000",
    "http://localhost:63342",
    "http://localhost:5173",  # Vite dev server
    "http://localhost:5174",  # Vite dev server alternate
    "http://localhost",
    "file://",
    "https://web-production-f564f.up.railway.app",  # Railway default domain
    "https://petmate-desktop-application.vercel.app",  # Vercel default domain
    "https://www.petmateanimalclinic.com",  # Custom frontend domain (no trailing slash)
    "https://petmateanimalclinic.com",  # Custom frontend domain without www
]

# Allow credentials so cookies (session, csrf) are accepted from the frontend dev origin
CORS_ALLOW_CREDENTIALS = True

# In dev it's okay to allow all origins but be explicit for clarity
CORS_ALLOW_ALL_ORIGINS = False  # Only for development

# Add frontend dev origins to CSRF trusted origins so Django accepts X-CSRFToken from them
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5174",
    "http://localhost:5173",
    "http://localhost:3000",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5174",
    "http://127.0.0.1:3000",
    "https://triggerless-brianna-pseudoviperous.ngrok-free.dev",
    "https://web-production-f564f.up.railway.app",
    "https://petmate-management.vercel.app",
    "https://petmate-desktop-application.vercel.app",
    "https://www.petmateanimalclinic.com",  # Custom frontend domain
    "https://petmateanimalclinic.com",  # Custom frontend domain without www
    "https://api.petmateanimalclinic.com",  # Custom backend domain
]

# Add your deployed frontend URL here after deployment
# Example: "https://your-frontend-domain.vercel.app"
if os.getenv('FRONTEND_URL'):
    CSRF_TRUSTED_ORIGINS.append(os.getenv('FRONTEND_URL'))
    
# Add Railway domain
if os.getenv('RAILWAY_PUBLIC_DOMAIN'):
    railway_domain = f"https://{os.getenv('RAILWAY_PUBLIC_DOMAIN')}"
    CSRF_TRUSTED_ORIGINS.append(railway_domain)

# django-cors-headers uses CORS_ALLOW_HEADERS (not CORS_ALLOWED_HEADERS).
# If the frontend sends non-simple headers (e.g. Cache-Control), the browser will
# preflight and will fail unless they are listed here.
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'cache-control',  # allow fetch/axios default cache header
]

# iOS Safari compatibility: Allow browser to see Set-Cookie headers
CORS_EXPOSE_HEADERS = [
    'set-cookie',
]

SESSION_COOKIE_AGE = 3600  # 1 hour
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True

# Ensure cookies work cross-site from Vercel to Railway over HTTPS
# iOS Safari compatibility: Use environment-based settings
SESSION_COOKIE_SECURE = not DEBUG  # True in production (HTTPS required), False in dev
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = 'None' if not DEBUG else 'Lax'  # None for cross-origin in production
CSRF_COOKIE_SAMESITE = 'None' if not DEBUG else 'Lax'
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False  # Frontend needs to read csrftoken

# Partitioned cookies for iOS Safari (Chrome also supports this)
# This helps with iOS Safari's ITP (Intelligent Tracking Prevention)
SESSION_COOKIE_NAME = 'sessionid'
CSRF_COOKIE_NAME = 'csrftoken'

# Don't set domain so cookie works for the backend domain
# SESSION_COOKIE_DOMAIN = None  # Let Django use the request domain

# Honor X-Forwarded-Proto so Django knows requests are HTTPS behind the proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')